using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Edit_Exclude_Dict
{
    internal class MS_LCID
    {
        public MS_LCID() { }

        // The values in this array are from the table in Appendix A: Product Behavior 
        // of Microsoft's  Windows Language Code Identifier (LCID) Reference document.
        static readonly string[,] MS_LCID_Array = {
            { "Afar" }, { "1000" },
            { "Afar Djibouti" }, { "1000" },
            { "Afar Eritrea" }, { "1000" },
            { "Afar Ethiopia" }, { "1000" },
            { "Afrikaans" }, { "0036" },
            { "Afrikaans Namibia" }, { "1000" },
            { "Afrikaans South Africa" }, { "0436" },
            { "Aghem" }, { "1000" },
            { "Aghem Cameroon" }, { "1000" },
            { "Akan" }, { "1000" },
            { "Akan Ghana" }, { "1000" },
            { "Albanian" }, { "001C" },
            { "Albanian Albania" }, { "041C" },
            { "Albanian North Macedonia" }, { "1000" },
            { "Alsatian" }, { "0084" },
            { "Alsatian France" }, { "0484" },
            { "Alsatian Liechtenstein" }, { "1000" },
            { "Alsatian Switzerland" }, { "1000" },
            { "Amharic" }, { "005E" },
            { "Amharic Ethiopia" }, { "045E" },
            { "Arabic" }, { "0001" },
            { "Arabic Algeria" }, { "1401" },
            { "Arabic Bahrain" }, { "3C01" },
            { "Arabic Chad" }, { "1000" },
            { "Arabic Comoros" }, { "1000" },
            { "Arabic Djibouti" }, { "1000" },
            { "Arabic Egypt" }, { "0c01" },
            { "Arabic Eritrea" }, { "1000" },
            { "Arabic Iraq" }, { "0801" },
            { "Arabic Israel" }, { "1000" },
            { "Arabic Jordan" }, { "2C01" },
            { "Arabic Kuwait" }, { "3401" },
            { "Arabic Lebanon" }, { "3001" },
            { "Arabic Libya" }, { "1001" },
            { "Arabic Mauritania" }, { "1000" },
            { "Arabic Morocco" }, { "1801" },
            { "Arabic Oman" }, { "2001" },
            { "Arabic Palestinian Authority" }, { "1000" },
            { "Arabic Qatar" }, { "4001" },
            { "Arabic Saudi Arabia" }, { "0401" },
            { "Arabic Somalia" }, { "1000" },
            { "Arabic South Sudan" }, { "1000" },
            { "Arabic Sudan" }, { "1000" },
            { "Arabic Syria" }, { "2801" },
            { "Arabic Tunisia" }, { "1C01" },
            { "Arabic U.A.E." }, { "3801" },
            { "Arabic World" }, { "1000" },
            { "Arabic Yemen" }, { "2401" },
            { "Armenian" }, { "002B" },
            { "Armenian Armenia" }, { "042B" },
            { "Assamese" }, { "004D" },
            { "Assamese India" }, { "044D" },
            { "Asturian" }, { "1000" },
            { "Asturian Spain" }, { "1000" },
            { "Asu" }, { "1000" },
            { "Asu Tanzania" }, { "1000" },
            { "Azerbaijani (Cyrillic)" }, { "742C" },
            { "Azerbaijani (Cyrillic) Azerbaijan" }, { "082C" },
            { "Azerbaijani (Latin)" }, { "002C" },
            { "Azerbaijani (Latin)" }, { "782C" },
            { "Azerbaijani (Latin) Azerbaijan" }, { "042C" },
            { "Bafia" }, { "1000" },
            { "Bafia Cameroon" }, { "1000" },
            { "Bamanankan" }, { "1000" },
            { "Bamanankan (Latin) Mali" }, { "1000" },
            { "Bangla" }, { "0045" },
            { "Bangla Bangladesh" }, { "0845" },
            { "Bangla India" }, { "0445" },
            { "Basaa" }, { "1000" },
            { "Basaa Cameroon" }, { "1000" },
            { "Bashkir" }, { "006D" },
            { "Bashkir Russia" }, { "046D" },
            { "Basque" }, { "002D" },
            { "Basque Spain" }, { "042D" },
            { "Belarusian" }, { "0023" },
            { "Belarusian Belarus" }, { "0423" },
            { "Bemba" }, { "1000" },
            { "Bemba Zambia" }, { "1000" },
            { "Bena" }, { "1000" },
            { "Bena Tanzania" }, { "1000" },
            { "Bhojpuri" }, { "1000" },
            { "Bhojpuri (Devanagari)" }, { "1000" },
            { "Bhojpuri (Devanagari) India" }, { "1000" },
            { "Blin" }, { "1000" },
            { "Blin Eritrea" }, { "1000" },
            { "Bodo" }, { "1000" },
            { "Bodo India" }, { "1000" },
            { "Bosnian (Cyrillic)" }, { "641A" },
            { "Bosnian (Cyrillic) Bosnia and Herzegovina" }, { "201A" },
            { "Bosnian (Latin)" }, { "681A" },
            { "Bosnian (Latin)" }, { "781A" },
            { "Bosnian (Latin) Bosnia and Herzegovina" }, { "141A" },
            { "Breton" }, { "007E" },
            { "Breton France" }, { "047E" },
            { "Bulgarian" }, { "0002" },
            { "Bulgarian Bulgaria" }, { "0402" },
            { "Burmese" }, { "0055" },
            { "Burmese Myanmar" }, { "0455" },
            { "Catalan" }, { "0003" },
            { "Catalan Andorra" }, { "1000" },
            { "Catalan France" }, { "1000" },
            { "Catalan Italy" }, { "1000" },
            { "Catalan Spain" }, { "0403" },
            { "Cebuano" }, { "1000" },
            { "Cebuan (Latin)" }, { "1000" },
            { "Cebuan (Latin) Philippines" }, { "1000" },
            { "Central Atlas Tamazight (Arabic) Morocco" }, { "045F" },
            { "Central Atlas Tamazight (Latin) Morocco" }, { "1000" },
            { "Central Kurdish" }, { "0092" },
            { "Central Kurdish" }, { "7c92" },
            { "Central Kurdish Iraq" }, { "0492" },
            { "Chakma" }, { "1000" },
            { "Chakma Chakma" }, { "1000" },
            { "Chakma Bangladesh" }, { "1000" },
            { "Chakma India" }, { "1000" },
            { "Chechen Russia" }, { "1000" },
            { "Cherokee" }, { "005C" },
            { "Cherokee" }, { "7c5C" },
            { "Cherokee United States" }, { "045C" },
            { "Chiga" }, { "1000" },
            { "Chiga Uganda" }, { "1000" },
            { "Chinese (Simplified)" }, { "0004" },
            { "Chinese (Simplified)" }, { "7804" },
            { "Chinese (Simplified) People's Republic of China" }, { "0804" },
            { "Chinese (Simplified) Singapore" }, { "1004" },
            { "Chinese (Traditional)" }, { "7C04" },
            { "Chinese (Traditional) Hong Kong S.A.R." }, { "0C04" },
            { "Chinese (Traditional) Macao S.A.R." }, { "1404" },
            { "Chinese (Traditional) Taiwan" }, { "0404" },
            { "Church Slavic Russia" }, { "1000" },
            { "Chuvash" }, { "1000" },
            { "Chuvash (Cyrillic)" }, { "1000" },
            { "Chuvash (Cyrillic) Russia" }, { "1000" },
            { "Congo Swahili" }, { "1000" },
            { "Congo Swahili Congo DRC" }, { "1000" },
            { "Cornish" }, { "1000" },
            { "Cornish United Kingdom" }, { "1000" },
            { "Corsican" }, { "0083" },
            { "Corsican France" }, { "0483" },
            { "Croatian" }, { "001A" },
            { "Croatian Croatia" }, { "041A" },
            { "Croatian (Latin) Bosnia and Herzegovina" }, { "101A" },
            { "Czech" }, { "0005" },
            { "Czech Czech Republic" }, { "0405" },
            { "Danish" }, { "0006" },
            { "Danish Denmark" }, { "0406" },
            { "Danish Greenland" }, { "1000" },
            { "Dari" }, { "008C" },
            { "Dari Afghanistan" }, { "048C" },
            { "Divehi" }, { "0065" },
            { "Divehi Maldives" }, { "0465" },
            { "Duala" }, { "1000" },
            { "Duala Cameroon" }, { "1000" },
            { "Dutch" }, { "0013" },
            { "Dutch Aruba" }, { "1000" },
            { "Dutch Belgium" }, { "0813" },
            { "Dutch Bonaire, Sint Eustatius and Saba" }, { "1000" },
            { "Dutch Curaçao" }, { "1000" },
            { "Dutch Netherlands" }, { "0413" },
            { "Dutch Sint Maarten" }, { "1000" },
            { "Dutch Suriname" }, { "1000" },
            { "Dzongkha" }, { "1000" },
            { "Dzongkha Bhutan" }, { "0C51" },
            { "Embu" }, { "1000" },
            { "Embu Kenya" }, { "1000" },
            { "English" }, { "0009" },
            { "English American Samoa" }, { "1000" },
            { "English Anguilla" }, { "1000" },
            { "English Antigua and Barbuda" }, { "1000" },
            { "English Australia" }, { "0C09" },
            { "English Austria" }, { "1000" },
            { "English Bahamas" }, { "1000" },
            { "English Barbados" }, { "1000" },
            { "English Belgium" }, { "1000" },
            { "English Belize" }, { "2809" },
            { "English Bermuda" }, { "1000" },
            { "English Botswana" }, { "1000" },
            { "English British Indian Ocean Territory" }, { "1000" },
            { "English British Virgin Islands" }, { "1000" },
            { "English Burundi" }, { "1000" },
            { "English Cameroon" }, { "1000" },
            { "English Canada" }, { "1009" },
            { "English Caribbean" }, { "2409" },
            { "English Cayman Islands" }, { "1000" },
            { "English Christmas Island" }, { "1000" },
            { "English Cocos [Keeling] Islands" }, { "1000" },
            { "English Cook Islands" }, { "1000" },
            { "English Cyprus" }, { "1000" },
            { "English Denmark" }, { "1000" },
            { "English Dominica" }, { "1000" },
            { "English Eritrea" }, { "1000" },
            { "English Europe" }, { "1000" },
            { "English Falkland Islands" }, { "1000" },
            { "English Finland" }, { "1000" },
            { "English Fiji" }, { "1000" },
            { "English Gambia" }, { "1000" },
            { "English Germany" }, { "1000" },
            { "English Ghana" }, { "1000" },
            { "English Gibraltar" }, { "1000" },
            { "English Grenada" }, { "1000" },
            { "English Guam" }, { "1000" },
            { "English Guernsey" }, { "1000" },
            { "English Guyana" }, { "1000" },
            { "English Hong Kong" }, { "3C09" },
            { "English India" }, { "4009" },
            { "English Ireland" }, { "1809" },
            { "English Isle of Man" }, { "1000" },
            { "English Israel" }, { "1000" },
            { "English Jamaica" }, { "2009" },
            { "English Jersey" }, { "1000" },
            { "English Kenya" }, { "1000" },
            { "English Kiribati" }, { "1000" },
            { "English Lesotho" }, { "1000" },
            { "English Liberia" }, { "1000" },
            { "English Macao SAR" }, { "1000" },
            { "English Madagascar" }, { "1000" },
            { "English Malawi" }, { "1000" },
            { "English Malaysia" }, { "4409" },
            { "English Maldives" }, { "1000" },
            { "English Malta" }, { "1000" },
            { "English Marshall Islands" }, { "1000" },
            { "English Mauritius" }, { "1000" },
            { "English Micronesia" }, { "1000" },
            { "English Montserrat" }, { "1000" },
            { "English Namibia" }, { "1000" },
            { "English Nauru" }, { "1000" },
            { "English Netherlands" }, { "1000" },
            { "English New Zealand" }, { "1409" },
            { "English Nigeria" }, { "1000" },
            { "English Niue" }, { "1000" },
            { "English Norfolk Island" }, { "1000" },
            { "English Northern Mariana Islands" }, { "1000" },
            { "English Pakistan" }, { "1000" },
            { "English Palau" }, { "1000" },
            { "English Papua New Guinea" }, { "1000" },
            { "English Pitcairn Islands" }, { "1000" },
            { "English Puerto Rico" }, { "1000" },
            { "English Republic of the Philippines" }, { "3409" },
            { "English Rwanda" }, { "1000" },
            { "English Saint Kitts and Nevis" }, { "1000" },
            { "English Saint Lucia" }, { "1000" },
            { "English Saint Vincent and the Grenadines" }, { "1000" },
            { "English Samoa" }, { "1000" },
            { "English Seychelles" }, { "1000" },
            { "English Sierra Leone" }, { "1000" },
            { "English Singapore" }, { "4809" },
            { "English Sint Maarten" }, { "1000" },
            { "English Slovenia" }, { "1000" },
            { "English Solomon Islands" }, { "1000" },
            { "English South Africa" }, { "1C09" },
            { "English South Sudan" }, { "1000" },
            { "English St Helena, Ascension, Tristan da Cunha" }, { "1000" },
            { "English Sudan" }, { "1000" },
            { "English Swaziland" }, { "1000" },
            { "English Sweden" }, { "1000" },
            { "English Switzerland" }, { "1000" },
            { "English Tanzania" }, { "1000" },
            { "English Tokelau" }, { "1000" },
            { "English Tonga" }, { "1000" },
            { "English Trinidad and Tobago" }, { "2c09" },
            { "English Turks and Caicos Islands" }, { "1000" },
            { "English Tuvalu" }, { "1000" },
            { "English Uganda" }, { "1000" },
            { "English United Arab Emirates" }, { "4C09" },
            { "English United Kingdom" }, { "0809" },
            { "English United States" }, { "0409" },
            { "English US Minor Outlying Islands" }, { "1000" },
            { "English US Virgin Islands" }, { "1000" },
            { "English Vanuatu" }, { "1000" },
            { "English World" }, { "1000" },
            { "English Zambia" }, { "1000" },
            { "English Zimbabwe" }, { "3009" },
            { "Esperanto" }, { "1000" },
            { "Esperanto World" }, { "1000" },
            { "Estonian" }, { "0025" },
            { "Estonian Estonia" }, { "0425" },
            { "Ewe" }, { "1000" },
            { "Ewe Ghana" }, { "1000" },
            { "Ewe Togo" }, { "1000" },
            { "Ewondo" }, { "1000" },
            { "Ewondo Cameroon" }, { "1000" },
            { "Faroese" }, { "0038" },
            { "Faroese Denmark" }, { "1000" },
            { "Faroese Faroe Islands" }, { "0438" },
            { "Filipino" }, { "0064" },
            { "Filipino Philippines" }, { "0464" },
            { "Finnish" }, { "000B" },
            { "Finnish Finland" }, { "040B" },
            { "French" }, { "000C" },
            { "French Algeria" }, { "1000" },
            { "French Belgium" }, { "080C" },
            { "French Benin" }, { "1000" },
            { "French Burkina Faso" }, { "1000" },
            { "French Burundi" }, { "1000" },
            { "French Cameroon" }, { "2c0C" },
            { "French Canada" }, { "0c0C" },
            { "French Caribbean" }, { "1C0C" },
            { "French Central African Republic" }, { "1000" },
            { "French Chad" }, { "1000" },
            { "French Comoros" }, { "1000" },
            { "French Congo" }, { "1000" },
            { "French Congo, DRC" }, { "240C" },
            { "French Côte d'Ivoire" }, { "300C" },
            { "French Djibouti" }, { "1000" },
            { "French Equatorial Guinea" }, { "1000" },
            { "French France" }, { "040C" },
            { "French French Guiana" }, { "1000" },
            { "French French Polynesia" }, { "1000" },
            { "French Gabon" }, { "1000" },
            { "French Guadeloupe" }, { "1000" },
            { "French Guinea" }, { "1000" },
            { "French Haiti" }, { "3c0C" },
            { "French Luxembourg" }, { "140C" },
            { "French Madagascar" }, { "1000" },
            { "French Mali" }, { "340C" },
            { "French Martinique" }, { "1000" },
            { "French Mauritania" }, { "1000" },
            { "French Mauritius" }, { "1000" },
            { "French Mayotte" }, { "1000" },
            { "French Morocco" }, { "380C" },
            { "French New Caledonia" }, { "1000" },
            { "French Niger" }, { "1000" },
            { "French Principality of Monaco" }, { "180C" },
            { "French Reunion" }, { "200C" },
            { "French Rwanda" }, { "1000" },
            { "French Saint Barthélemy" }, { "1000" },
            { "French Saint Martin" }, { "1000" },
            { "French Saint Pierre and Miquelon" }, { "1000" },
            { "French Senegal" }, { "280C" },
            { "French Seychelles" }, { "1000" },
            { "French Switzerland" }, { "100C" },
            { "French Syria" }, { "1000" },
            { "French" }, { "1000" },
            { "French Tunisia" }, { "1000" },
            { "French Vanuatu" }, { "1000" },
            { "French Wallis and Futuna" }, { "1000" },
            { "Frisian" }, { "0062" },
            { "Frisian Netherlands" }, { "0462" },
            { "Friulian" }, { "1000" },
            { "Friulian Italy" }, { "1000" },
            { "Fulah" }, { "0067" },
            { "Fulah (Latin)" }, { "7C67" },
            { "Fulah (Latin) Burkina Faso" }, { "1000" },
            { "Fulah Cameroon" }, { "1000" },
            { "Fulah (Latin) Cameroon" }, { "1000" },
            { "Fulah (Latin) Gambia" }, { "1000" },
            { "Fulah (Latin) Ghana" }, { "1000" },
            { "Fulah Guinea" }, { "1000" },
            { "Fulah (Latin) Guinea" }, { "1000" },
            { "Fulah (Latin) Guinea-Bissau" }, { "1000" },
            { "Fulah (Latin) Liberia" }, { "1000" },
            { "Fulah Mauritania" }, { "1000" },
            { "Fulah (Latin) Mauritania" }, { "1000" },
            { "Fulah (Latin) Niger" }, { "1000" },
            { "Fulah Nigeria" }, { "0467" },
            { "Fulah (Latin) Nigeria" }, { "0467" },
            { "Fulah Senegal" }, { "0867" },
            { "Fulah (Latin) Sierra Leone" }, { "1000" },
            { "Galician" }, { "0056" },
            { "Galician Spain" }, { "0456" },
            { "Ganda" }, { "1000" },
            { "Ganda Uganda" }, { "1000" },
            { "Georgian" }, { "0037" },
            { "Georgian Georgia" }, { "0437" },
            { "German" }, { "0007" },
            { "German Austria" }, { "0C07" },
            { "German Belgium" }, { "1000" },
            { "German Germany" }, { "0407" },
            { "German Italy" }, { "1000" },
            { "German Liechtenstein" }, { "1407" },
            { "German Luxembourg" }, { "1007" },
            { "German Switzerland" }, { "0807" },
            { "Greek" }, { "0008" },
            { "Greek Cyprus" }, { "1000" },
            { "Greek Greece" }, { "0408" },
            { "Greenlandic" }, { "006F" },
            { "Greenlandic Greenland" }, { "046F" },
            { "Guarani" }, { "0074" },
            { "Guarani Paraguay" }, { "0474" },
            { "Gujarati" }, { "0047" },
            { "Gujarati India" }, { "0447" },
            { "Gusii" }, { "1000" },
            { "Gusii Kenya" }, { "1000" },
            { "Haryanvi" }, { "1000" },
            { "Haryanvi (Devanagari)" }, { "1000" },
            { "Haryanvi (Devanagari) India" }, { "1000" },
            { "Hausa (Latin)" }, { "0068" },
            { "Hausa (Latin)" }, { "7C68" },
            { "Hausa (Latin) Ghana" }, { "1000" },
            { "Hausa (Latin) Niger" }, { "1000" },
            { "Hausa (Latin) Nigeria" }, { "0468" },
            { "Hawaiian" }, { "0075" },
            { "Hawaiian United States" }, { "0475" },
            { "Hebrew" }, { "000D" },
            { "Hebrew Israel" }, { "040D" },
            { "Hindi" }, { "0039" },
            { "Hindi India" }, { "0439" },
            { "Hindi (Latin)" }, { "1000" },
            { "Hindi (Latin) India" }, { "1000" },
            { "Hungarian" }, { "000E" },
            { "Hungarian Hungary" }, { "040E" },
            { "Icelandic" }, { "000F" },
            { "Icelandic Iceland" }, { "040F" },
            { "Igbo" }, { "0070" },
            { "Igbo Nigeria" }, { "0470" },
            { "Indonesian" }, { "0021" },
            { "Indonesian Indonesia" }, { "0421" },
            { "Interlingua" }, { "1000" },
            { "Interlingua France" }, { "1000" },
            { "Interlingua World" }, { "1000" },
            { "Inuktitut (Latin)" }, { "005D" },
            { "Inuktitut (Latin)" }, { "7C5D" },
            { "Inuktitut (Latin) Canada" }, { "085D" },
            { "Inuktitut (Syllabics)" }, { "785D" },
            { "Inuktitut (Syllabics) Canada" }, { "045d" },
            { "Irish" }, { "003C" },
            { "Irish Ireland" }, { "083C" },
            { "Italian" }, { "0010" },
            { "Italian Italy" }, { "0410" },
            { "Italian San Marino" }, { "1000" },
            { "Italian Switzerland" }, { "0810" },
            { "Italian Vatican City" }, { "1000" },
            { "Japanese" }, { "0011" },
            { "Japanese Japan" }, { "0411" },
            { "Javanese" }, { "1000" },
            { "Javanese Latin" }, { "1000" },
            { "Javanese Latin, Indonesia" }, { "1000" },
            { "Jola-Fonyi" }, { "1000" },
            { "Jola-Fonyi Senegal" }, { "1000" },
            { "Kabuverdianu" }, { "1000" },
            { "Kabuverdianu Cabo Verde" }, { "1000" },
            { "Kabyle" }, { "1000" },
            { "Kabyle Algeria" }, { "1000" },
            { "Kaingang" }, { "1000" },
            { "Kaingang (Latin)" }, { "1000" },
            { "Kaingang (Latin) Brazil" }, { "1000" },
            { "Kako" }, { "1000" },
            { "Kako Cameroon" }, { "1000" },
            { "Kalenjin" }, { "1000" },
            { "Kalenjin Kenya" }, { "1000" },
            { "Kamba" }, { "1000" },
            { "Kamba Kenya" }, { "1000" },
            { "Kannada" }, { "004B" },
            { "Kannada India" }, { "044B" },
            { "Kanuri (Latin) Nigeria" }, { "0471" },
            { "Kashmiri" }, { "0060" },
            { "Kashmiri Perso-Arabic" }, { "0460" },
            { "Kashmiri Perso-Arabic" }, { "1000" },
            { "Kashmiri (Devanagari) India" }, { "0860" },
            { "Kazakh" }, { "003F" },
            { "Kazakh Kazakhstan" }, { "043F" },
            { "Khmer" }, { "0053" },
            { "Khmer Cambodia" }, { "0453" },
            { "K'iche" }, { "0086" },
            { "K'iche Guatemala" }, { "0486" },
            { "Kikuyu" }, { "1000" },
            { "Kikuyu Kenya" }, { "1000" },
            { "Kinyarwanda" }, { "0087" },
            { "Kinyarwanda Rwanda" }, { "0487" },
            { "Kiswahili" }, { "0041" },
            { "Kiswahili Kenya" }, { "0441" },
            { "Kiswahili Tanzania" }, { "1000" },
            { "Kiswahili Uganda" }, { "1000" },
            { "Konkani" }, { "0057" },
            { "Konkani India" }, { "0457" },
            { "Korean" }, { "0012" },
            { "Korean Korea" }, { "0412" },
            { "Korean North Korea" }, { "1000" },
            { "Koyra Chiini" }, { "1000" },
            { "Koyra Chiini Mali" }, { "1000" },
            { "Koyraboro Senni" }, { "1000" },
            { "Koyraboro Senni Mali" }, { "1000" },
            { "Kwasio" }, { "1000" },
            { "Kwasio Cameroon" }, { "1000" },
            { "Kyrgyz" }, { "0040" },
            { "Kyrgyz Kyrgyzstan" }, { "0440" },
            { "Kurdish Perso-Arabic, Iran" }, { "1000" },
            { "Lakota" }, { "1000" },
            { "Lakota United States" }, { "1000" },
            { "Langi" }, { "1000" },
            { "Langi Tanzania" }, { "1000" },
            { "Lao" }, { "0054" },
            { "Lao Lao P.D.R." }, { "0454" },
            { "Latin Vatican City" }, { "0476" },
            { "Latvian" }, { "0026" },
            { "Latvian Latvia" }, { "0426" },
            { "Lingala" }, { "1000" },
            { "Lingala Angola" }, { "1000" },
            { "Lingala Central African Republic" }, { "1000" },
            { "Lingala Congo" }, { "1000" },
            { "Lingala Congo DRC" }, { "1000" },
            { "Lithuanian" }, { "0027" },
            { "Lithuanian Lithuania" }, { "0427" },
            { "Low German" }, { "1000" },
            { "Low German Germany" }, { "1000" },
            { "Low German Netherlands" }, { "1000" },
            { "Lower Sorbian" }, { "7C2E" },
            { "Lower Sorbian Germany" }, { "082E" },
            { "Luba-Katanga" }, { "1000" },
            { "Luba-Katanga Congo DRC" }, { "1000" },
            { "Luo" }, { "1000" },
            { "Luo Kenya" }, { "1000" },
            { "Luxembourgish" }, { "006E" },
            { "Luxembourgish Luxembourg" }, { "046E" },
            { "Luyia" }, { "1000" },
            { "Luyia Kenya" }, { "1000" },
            { "Macedonian" }, { "002F" },
            { "Macedonian North Macedonia" }, { "042F" },
            { "Machame" }, { "1000" },
            { "Machame Tanzania" }, { "1000" },
            { "Makhuwa-Meetto" }, { "1000" },
            { "Makhuwa-Meetto Mozambique" }, { "1000" },
            { "Makonde" }, { "1000" },
            { "Makonde Tanzania" }, { "1000" },
            { "Malagasy" }, { "1000" },
            { "Malagasy Madagascar" }, { "1000" },
            { "Malay" }, { "003E" },
            { "Malay Brunei Darussalam" }, { "083E" },
            { "Malay Malaysia" }, { "043E" },
            { "Malayalam" }, { "004C" },
            { "Malayalam India" }, { "044C" },
            { "Maltese" }, { "003A" },
            { "Maltese Malta" }, { "043A" },
            { "Manx" }, { "1000" },
            { "Manx Isle of Man" }, { "1000" },
            { "Maori" }, { "0081" },
            { "Maori New Zealand" }, { "0481" },
            { "Mapudungun" }, { "007A" },
            { "Mapudungun Chile" }, { "047A" },
            { "Marathi" }, { "004E" },
            { "Marathi India" }, { "044E" },
            { "Masai" }, { "1000" },
            { "Masai Kenya" }, { "1000" },
            { "Masai Tanzania" }, { "1000" },
            { "Mazanderani Iran" }, { "1000" },
            { "Meru" }, { "1000" },
            { "Meru Kenya" }, { "1000" },
            { "Meta'" }, { "1000" },
            { "Meta' Cameroon" }, { "1000" },
            { "Mohawk" }, { "007C" },
            { "Mohawk Canada" }, { "047C" },
            { "Mongolian (Cyrillic)" }, { "0050" },
            { "Mongolian (Cyrillic)" }, { "7850" },
            { "Mongolian (Cyrillic) Mongolia" }, { "0450" },
            { "Mongolian (Traditional Mongolian)" }, { "7C50" },
            { "Mongolian (Traditional Mongolian) People's Republic of China" }, { "0850" },
            { "Mongolian (Traditional Mongolian) Mongolia" }, { "0C50" },
            { "Morisyen" }, { "1000" },
            { "Morisyen Mauritius" }, { "1000" },
            { "Mundang" }, { "1000" },
            { "Mundang Cameroon" }, { "1000" },
            { "N'ko" }, { "1000" },
            { "N'ko Guinea" }, { "1000" },
            { "Nama" }, { "1000" },
            { "Nama Namibia" }, { "1000" },
            { "Nepali" }, { "0061" },
            { "Nepali India" }, { "0861" },
            { "Nepali Nepal" }, { "0461" },
            { "Ngiemboon" }, { "1000" },
            { "Ngiemboon Cameroon" }, { "1000" },
            { "Ngomba" }, { "1000" },
            { "Ngomba Cameroon" }, { "1000" },
            { "Nheengatu" }, { "1000" },
            { "Nheengatu (Latin)" }, { "1000" },
            { "Nheengatu (Latin) Brazil" }, { "1000" },
            { "Nheengatu (Latin) Colombia" }, { "1000" },
            { "Nheengatu (Latin) Venezuela" }, { "1000" },
            { "Northern Luri Iraq" }, { "1000" },
            { "Northern Luri Iran" }, { "1000" },
            { "North Ndebele" }, { "1000" },
            { "North Ndebele Zimbabwe" }, { "1000" },
            { "Norwegian (Bokmal)" }, { "0014" },
            { "Norwegian (Bokmal)" }, { "7C14" },
            { "Norwegian (Bokmal) Norway" }, { "0414" },
            { "Norwegian (Nynorsk)" }, { "7814" },
            { "Norwegian (Nynorsk) Norway" }, { "0814" },
            { "Norwegian Bokmål Svalbard and Jan Mayen" }, { "1000" },
            { "Nuer" }, { "1000" },
            { "Nuer Sudan" }, { "1000" },
            { "Nuer South Sudan" }, { "1000" },
            { "Nyankole" }, { "1000" },
            { "Nyankole Uganda" }, { "1000" },
            { "Occitan" }, { "0082" },
            { "Occitan France" }, { "0482" },
            { "Occitan Spain" }, { "1000" },
            { "Odia" }, { "0048" },
            { "Odia India" }, { "0448" },
            { "Oromo" }, { "0072" },
            { "Oromo Ethiopia" }, { "0472" },
            { "Oromo Kenya" }, { "1000" },
            { "Ossetian" }, { "1000" },
            { "Ossetian Cyrillic, Georgia" }, { "1000" },
            { "Ossetian Cyrillic, Russia" }, { "1000" },
            { "Pashto" }, { "0063" },
            { "Pashto Afghanistan" }, { "0463" },
            { "Pashto Pakistan" }, { "1000" },
            { "Persian" }, { "0029" },
            { "Persian Afghanistan" }, { "1000" },
            { "Persian Iran" }, { "0429" },
            { "Polish" }, { "0015" },
            { "Polish Poland" }, { "0415" },
            { "Portuguese" }, { "0016" },
            { "Portuguese Angola" }, { "1000" },
            { "Portuguese Brazil" }, { "0416" },
            { "Portuguese Cabo Verde" }, { "1000" },
            { "Portuguese Equatorial Guinea" }, { "1000" },
            { "Portuguese Guinea-Bissau" }, { "1000" },
            { "Portuguese Luxembourg" }, { "1000" },
            { "Portuguese Macao SAR" }, { "1000" },
            { "Portuguese Mozambique" }, { "1000" },
            { "Portuguese Portugal" }, { "0816" },
            { "Portuguese São Tomé and Príncipe" }, { "1000" },
            { "Portuguese Switzerland" }, { "1000" },
            { "Portuguese Timor-Leste" }, { "1000" },
            { "Prussian" }, { "1000" },
            { "Pseudo Language Pseudo locale for east Asian/complex script localization testing" }, { "05FE" },
            { "Pseudo Language Pseudo locale used for localization testing" }, { "0501" },
            { "Pseudo Language Pseudo locale used for localization testing of mirrored locales" }, { "09FF" },
            { "Punjabi" }, { "0046" },
            { "Punjabi" }, { "7C46" },
            { "Punjabi India" }, { "0446" },
            { "Punjabi Islamic Republic of Pakistan" }, { "0846" },
            { "Quechua" }, { "006B" },
            { "Quechua Bolivia" }, { "046B" },
            { "Quechua Ecuador" }, { "086B" },
            { "Quechua Peru" }, { "0C6B" },
            { "Rajasthani" }, { "1000" },
            { "Rajasthani (Devanagari)" }, { "1000" },
            { "Rajasthani (Devanagari) India" }, { "1000" },
            { "Ripuarian" }, { "1000" },
            { "Ripuarian Germany" }, { "1000" },
            { "Romanian" }, { "0018" },
            { "Romanian Moldova" }, { "0818" },
            { "Romanian Romania" }, { "0418" },
            { "Romansh" }, { "0017" },
            { "Romansh Switzerland" }, { "0417" },
            { "Rombo" }, { "1000" },
            { "Rombo Tanzania" }, { "1000" },
            { "Rundi" }, { "1000" },
            { "Rundi Burundi" }, { "1000" },
            { "Russian" }, { "0019" },
            { "Russian Belarus" }, { "1000" },
            { "Russian Kazakhstan" }, { "1000" },
            { "Russian Kyrgyzstan" }, { "1000" },
            { "Russian Moldova" }, { "0819" },
            { "Russian Russia" }, { "0419" },
            { "Russian Ukraine" }, { "1000" },
            { "Rwa" }, { "1000" },
            { "Rwa Tanzania" }, { "1000" },
            { "Saho" }, { "1000" },
            { "Saho Eritrea" }, { "1000" },
            { "Sakha" }, { "0085" },
            { "Sakha Russia" }, { "0485" },
            { "Samburu" }, { "1000" },
            { "Samburu Kenya" }, { "1000" },
            { "Sami (Inari)" }, { "703B" },
            { "Sami (Inari) Finland" }, { "243B" },
            { "Sami (Lule)" }, { "7C3B" },
            { "Sami (Lule) Norway" }, { "103B" },
            { "Sami (Lule) Sweden" }, { "143B" },
            { "Sami (Northern)" }, { "003B" },
            { "Sami (Northern) Finland" }, { "0C3B" },
            { "Sami (Northern) Norway" }, { "043B" },
            { "Sami (Northern) Sweden" }, { "083B" },
            { "Sami (Skolt)" }, { "743B" },
            { "Sami (Skolt) Finland" }, { "203B" },
            { "Sami (Southern)" }, { "783B" },
            { "Sami (Southern) Norway" }, { "183B" },
            { "Sami (Southern) Sweden" }, { "1C3B" },
            { "Sango" }, { "1000" },
            { "Sango Central African Republic" }, { "1000" },
            { "Sangu" }, { "1000" },
            { "Sangu Tanzania" }, { "1000" },
            { "Sanskrit" }, { "004F" },
            { "Sanskrit India" }, { "044F" },
            { "Sardinian" }, { "1000" },
            { "Sardinian (Latin)" }, { "1000" },
            { "Sardinian (Latin) Italy" }, { "1000" },
            { "Scottish Gaelic" }, { "0091" },
            { "Scottish Gaelic United Kingdom" }, { "0491" },
            { "Sena" }, { "1000" },
            { "Sena Mozambique" }, { "1000" },
            { "Serbian (Cyrillic)" }, { "6C1A" },
            { "Serbian (Cyrillic) Bosnia and Herzegovina" }, { "1C1A" },
            { "Serbian (Cyrillic) Montenegro" }, { "301A" },
            { "Serbian (Cyrillic) Serbia" }, { "281A" },
            { "Serbian (Cyrillic) Serbia and Montenegro (Former)" }, { "0C1A" },
            { "Serbian (Latin)" }, { "701A" },
            { "Serbian (Latin)" }, { "7C1A" },
            { "Serbian (Latin) Bosnia and Herzegovina" }, { "181A" },
            { "Serbian (Latin) Montenegro" }, { "2c1A" },
            { "Serbian (Latin) Serbia" }, { "241A" },
            { "Serbian (Latin) Serbia and Montenegro (Former)" }, { "081A" },
            { "Sesotho sa Leboa" }, { "006C" },
            { "Sesotho sa Leboa South Africa" }, { "046C" },
            { "Setswana" }, { "0032" },
            { "Setswana Botswana" }, { "0832" },
            { "Setswana South Africa" }, { "0432" },
            { "Shambala" }, { "1000" },
            { "Shambala Tanzania" }, { "1000" },
            { "Shona" }, { "1000" },
            { "Shona Latin" }, { "1000" },
            { "Shona Zimbabwe" }, { "1000" },
            { "Sindhi" }, { "0059" },
            { "Sindhi" }, { "7C59" },
            { "Sindhi Islamic Republic of Pakistan" }, { "0859" },
            { "Sinhala" }, { "005B" },
            { "Sinhala Sri Lanka" }, { "045B" },
            { "Slovak" }, { "001B" },
            { "Slovak Slovakia" }, { "041B" },
            { "Slovenian" }, { "0024" },
            { "Slovenian Slovenia" }, { "0424" },
            { "Soga" }, { "1000" },
            { "Soga Uganda" }, { "1000" },
            { "Somali" }, { "0077" },
            { "Somali Djibouti" }, { "1000" },
            { "Somali Ethiopia" }, { "1000" },
            { "Somali Kenya" }, { "1000" },
            { "Somali Somalia" }, { "0477" },
            { "Sotho" }, { "0030" },
            { "Sotho South Africa" }, { "0430" },
            { "South Ndebele" }, { "1000" },
            { "South Ndebele South Africa" }, { "1000" },
            { "Southern Sotho Lesotho" }, { "1000" },
            { "Spanish" }, { "000A" },
            { "Spanish Argentina" }, { "2C0A" },
            { "Spanish Belize" }, { "1000" },
            { "Spanish Bolivarian Republic of Venezuela" }, { "200A" },
            { "Spanish Bolivia" }, { "400A" },
            { "Spanish Brazil" }, { "1000" },
            { "Spanish Chile" }, { "340A" },
            { "Spanish Colombia" }, { "240A" },
            { "Spanish Costa Rica" }, { "140A" },
            { "Spanish Cuba" }, { "5c0A" },
            { "Spanish Dominican Republic" }, { "1c0A" },
            { "Spanish Ecuador" }, { "300A" },
            { "Spanish El Salvador" }, { "440A" },
            { "Spanish Equatorial Guinea" }, { "1000" },
            { "Spanish Guatemala" }, { "100A" },
            { "Spanish Honduras" }, { "480A" },
            { "Spanish Latin America" }, { "580A" },
            { "Spanish Mexico" }, { "080A" },
            { "Spanish Nicaragua" }, { "4C0A" },
            { "Spanish Panama" }, { "180A" },
            { "Spanish Paraguay" }, { "3C0A" },
            { "Spanish Peru" }, { "280A" },
            { "Spanish Philippines" }, { "1000" },
            { "Spanish Puerto Rico" }, { "500A" },
            { "Spanish Spain" }, { "040A" },
            { "Spanish Spain" }, { "0c0A" },
            { "Spanish United States" }, { "540A" },
            { "Spanish Uruguay" }, { "380A" },
            { "Standard Moroccan Tamazight" }, { "1000" },
            { "Standard Moroccan Tamazight Morocco" }, { "1000" },
            { "Standard Moroccan Tamazight Tifinagh" }, { "1000" },
            { "Swati" }, { "1000" },
            { "Swati South Africa" }, { "1000" },
            { "Swati Swaziland" }, { "1000" },
            { "Swedish" }, { "001D" },
            { "Swedish Åland Islands" }, { "1000" },
            { "Swedish Finland" }, { "081D" },
            { "Swedish Sweden" }, { "041D" },
            { "Syriac" }, { "005A" },
            { "Syriac Syria" }, { "045A" },
            { "Tachelhit" }, { "1000" },
            { "Tachelhit Tifinagh" }, { "1000" },
            { "Tachelhit Tifinagh, Morocco" }, { "1000" },
            { "Tachelhit (Latin)" }, { "1000" },
            { "Tachelhit (Latin) Morocco" }, { "1000" },
            { "Taita" }, { "1000" },
            { "Taita Kenya" }, { "1000" },
            { "Tajik (Cyrillic)" }, { "0028" },
            { "Tajik (Cyrillic)" }, { "7C28" },
            { "Tajik (Cyrillic) Tajikistan" }, { "0428" },
            { "Tamazight (Latin)" }, { "005F" },
            { "Tamazight (Latin)" }, { "7C5F" },
            { "Tamazight (Latin) Algeria" }, { "085F" },
            { "Tamil" }, { "0049" },
            { "Tamil India" }, { "0449" },
            { "Tamil Malaysia" }, { "1000" },
            { "Tamil Singapore" }, { "1000" },
            { "Tamil Sri Lanka" }, { "0849" },
            { "Tasawaq" }, { "1000" },
            { "Tasawaq Niger" }, { "1000" },
            { "Tatar" }, { "0044" },
            { "Tatar Russia" }, { "0444" },
            { "Telugu" }, { "004A" },
            { "Telugu India" }, { "044A" },
            { "Teso" }, { "1000" },
            { "Teso Kenya" }, { "1000" },
            { "Teso Uganda" }, { "1000" },
            { "Thai" }, { "001E" },
            { "Thai Thailand" }, { "041E" },
            { "Tibetan" }, { "0051" },
            { "Tibetan India" }, { "1000" },
            { "Tibetan People's Republic of China" }, { "0451" },
            { "Tigre" }, { "1000" },
            { "Tigre Eritrea" }, { "1000" },
            { "Tigrinya" }, { "0073" },
            { "Tigrinya Eritrea" }, { "0873" },
            { "Tigrinya Ethiopia" }, { "0473" },
            { "Tongan" }, { "1000" },
            { "Tongan Tonga" }, { "1000" },
            { "Tsonga" }, { "0031" },
            { "Tsonga South Africa" }, { "0431" },
            { "Turkish" }, { "001F" },
            { "Turkish Cyprus" }, { "1000" },
            { "Turkish Turkey" }, { "041F" },
            { "Turkmen" }, { "0042" },
            { "Turkmen Turkmenistan" }, { "0442" },
            { "Ukrainian" }, { "0022" },
            { "Ukrainian Ukraine" }, { "0422" },
            { "Upper Sorbian" }, { "002E" },
            { "Upper Sorbian Germany" }, { "042E" },
            { "Urdu" }, { "0020" },
            { "Urdu India" }, { "0820" },
            { "Urdu Islamic Republic of Pakistan" }, { "0420" },
            { "Uyghur" }, { "0080" },
            { "Uyghur People's Republic of China" }, { "0480" },
            { "Uzbek Perso-Arabic" }, { "1000" },
            { "Uzbek Perso-Arabic, Afghanistan" }, { "1000" },
            { "Uzbek (Cyrillic)" }, { "7843" },
            { "Uzbek (Cyrillic) Uzbekistan" }, { "0843" },
            { "Uzbek (Latin)" }, { "0043" },
            { "Uzbek (Latin)" }, { "7C43" },
            { "Uzbek (Latin) Uzbekistan" }, { "0443" },
            { "Vai" }, { "1000" },
            { "Vai" }, { "1000" },
            { "Vai Liberia" }, { "1000" },
            { "Vai (Latin) Liberia" }, { "1000" },
            { "Vai (Latin)" }, { "1000" },
            { "Valencian Spain" }, { "0803" },
            { "Venda" }, { "0033" },
            { "Venda South Africa" }, { "0433" },
            { "Vietnamese" }, { "002A" },
            { "Vietnamese Vietnam" }, { "042A" },
            { "Volapük" }, { "1000" },
            { "Volapük World" }, { "1000" },
            { "Vunjo" }, { "1000" },
            { "Vunjo Tanzania" }, { "1000" },
            { "Walser" }, { "1000" },
            { "Walser Switzerland" }, { "1000" },
            { "Welsh" }, { "0052" },
            { "Welsh United Kingdom" }, { "0452" },
            { "Wolaytta" }, { "1000" },
            { "Wolaytta Ethiopia" }, { "1000" },
            { "Wolof" }, { "0088" },
            { "Wolof Senegal" }, { "0488" },
            { "Xhosa" }, { "0034" },
            { "Xhosa South Africa" }, { "0434" },
            { "Yangben" }, { "1000" },
            { "Yangben Cameroon" }, { "1000" },
            { "Yi" }, { "0078" },
            { "Yi People's Republic of China" }, { "0478" },
            { "Yiddish World" }, { "043D" },
            { "Yoruba" }, { "006A" },
            { "Yoruba Benin" }, { "1000" },
            { "Yoruba Nigeria" }, { "046A" },
            { "Zarma" }, { "1000" },
            { "Zarma Niger" }, { "1000" },
            { "Zulu" }, { "0035" },
            { "Zulu South Africa" }, { "0435" },
            { "Yoruba Nigeria" }, { "046A" },
            { "Zarma" }, { "1000" },
            { "Zarma Niger" }, { "1000" },
            { "Zulu" }, { "0035" },
            { "Zulu South Africa" }, { "0435" }
        };
    }
}
 
